logging:
  level.bio.terra.cbas: ${BATCHANALYSIS_LOG_LEVEL:info}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: cbas
  application.version: ${cbas.version.gitHash:unknown}
  datasource:
    jdbc-url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    username: ${DATABASE_USER:cbas_user}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
  sql:
    init:
      mode: always


  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null # this prevents a problem serializing VisaCriterion in openapi where `type` is included a second time with null value

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
  liquibase:
    change-log: changelog/changelog.yaml

cbas:
  cbas-database:
    uri: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
    username: ${DATABASE_USER:cbas_user}
  cbas-api:
    # for POST/run_sets, the number of record IDs must be less than or equal to this value.
    runSetsMaximumRecordIds: 100
    maxWorkflowInputs: 200
    maxWorkflowOutputs: 300
    minSecondsBetweenRunStatusPolls: 30
    maxSmartPollRunUpdateSeconds: 3
    maxSmartPollRunSetUpdateSeconds: 6
  scheduler:
    # How often to check downstream services for health:
    healthCheckIntervalSeconds: 300

workflow-engines:
  cromwell:
    baseUri: "http://localhost:8000"
    debugApiLogging: false

wds:
  # For local testing, you can supply a value here. If unsupplied, we will fall back to looking up in Leonardo
  baseUri: "http://localhost:8001"
  instanceId: "15f36863-30a5-4cab-91f7-52be439f1175"
  apiV: "v0.2"
  debugApiLogging: false

leonardo:
  baseUri: "https://leonardo.dsde-dev.broadinstitute.org/"
  wdsAppTypeNames: ['WDS', 'CROMWELL']
  dependencyUrlCacheTtlSeconds: 300 # Refresh every 5 minutes
  debugApiLogging: false

dockstore:
  baseUri: "https://staging.dockstore.org/"

credentials:
  azure:
    tokenAcquisitionTimeoutSeconds: 5
    tokenCacheTtlSeconds: 300 # Refresh every 5 minutes
    # For local testing, you can supply a manual token override to avoid token acquisition logic:
    manualTokenOverride: "eyJhbGciOiJSUzI1NiIsImtpZCI6Inp4UnJ6aEw4OTBrYi1vVkZOWkdWUFlxSzYtSkI3RFRlTGVvMllTbzRtc1UiLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6InR3aXNlbWFuQGJyb2FkaW5zdGl0dXRlLm9yZyIsImdpdmVuX25hbWUiOiJUaG9tYXMiLCJmYW1pbHlfbmFtZSI6Ildpc2VtYW4iLCJuYW1lIjoiVGhvbWFzIFdpc2VtYW4iLCJpZHAiOiJnb29nbGUuY29tIiwiaWRwX2FjY2Vzc190b2tlbiI6InlhMjkuYTBBYlZiWTZPTW10WmhXRTI5MTRZRjdDdXNENTZFZkVKS1BmMDVCa1RHamF6VXQ3LXN2MXd0TTVMYzdHcURoU1Q2Tm1nTkNSeWZfU25ONlJfd1h6N3ZzOGF3RktHR2JkeGo1eWtTY3J0NlFYQ0JRTm8zeXEza1NzRmNJN25wV2M5UEZYTzFUMWYtVXozMVhIWkNBLUV2SzM0djVQODZwNnJNM1ZYYjFPOGFDZ1lLQWRrU0FSQVNGUUZXS3ZQbEQxZUNQdUV0NTRDT2ktTXZGVmZDSXcwMTc0IiwiZ29vZ2xlX2lkIjoiMTExNDI1MTI3NzgyODk3OTE5MjIxIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGNhZWxfZTl4dHdJQWdOZW1YY2N4d18xUWtlVjV1cF91NUFRTUMxMU5xNj1zOTYtYyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJzdWIiOiJhMzYxY2YxNS0xNTgxLTQ2ZDQtYmJkNC1mMGQ0NGFlNjkwODciLCJ0aWQiOiJmZDBiYzBlZi0xNzQ3LTRlZTYtYWIzZS1kNGQ2YmI4ODJkNDAiLCJhenAiOiJiYmQwN2Q0My0wMWNiLTRiNjktOGZkMC01NzQ2ZDlhNWM5ZmUiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2ODkyNzQxMDYsImF1ZCI6ImJiZDA3ZDQzLTAxY2ItNGI2OS04ZmQwLTU3NDZkOWE1YzlmZSIsImV4cCI6MTY4OTI3NzcwNiwiaXNzIjoiaHR0cHM6Ly90ZXJyYWRldmIyYy5iMmNsb2dpbi5jb20vZmQwYmMwZWYtMTc0Ny00ZWU2LWFiM2UtZDRkNmJiODgyZDQwL3YyLjAvIiwibmJmIjoxNjg5Mjc0MTA2fQ.gDxPXYYT15gpvN-tgbbt92TIS9450sKSHHZE9QxrSh9rhT4ypa4YvbnU9RDXWzW2t1CtUG3Xf9ySEvGXjDZo_0PpkApr1mfJ1TpgTx5Ko-vSfgj0c8X0CD-LDjy57DBz1jHLEZhXxF_Yzk-wcpKcx5ENfoYqCwShhFMYFnSrviG_0f7_LRL3nT_7nqDxWZIxk8N23B4ahapG6dpo_WibUrsYxjTR2iwVrtoyXI83cNDzeVAQOBqZIHq9VTpR0vd1HPeroeAGJjp9J5JEIrFYIvSdQMmxLUI8qr1_g_YYFq_AOJ-NjPr-6qgRJs8G-CX31EV9WaWBBgSFunDRiukIcA"

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
