logging:
  level.bio.terra.cbas: ${BATCHANALYSIS_LOG_LEVEL:info}

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: cbas
  application.version: ${cbas.version.gitHash:unknown}
  datasource:
    jdbc-url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    username: ${DATABASE_USER:cbas_user}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
  sql:
    init:
      mode: always


  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null # this prevents a problem serializing VisaCriterion in openapi where `type` is included a second time with null value

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
  liquibase:
    change-log: changelog/changelog.yaml

cbas:
  initialization.enabled: true
  context:
    # Should match wds.instanceId and sam.workspaceId:
    workspaceId: "00000000-0000-0000-0000-000000000000"
    # workspaceCreatedDate is supplied by Leo.
    # When testing locally, manually fill in this value, e.g. "2024-02-16T14:13:02.500743Z".
    workspaceCreatedDate:
  cbas-database:
    uri: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
    username: ${DATABASE_USER:cbas_user}
  cbas-api:
    # for POST/run_sets, the number of record IDs must be less than or equal to this value.
    runSetsMaximumRecordIds: 1000
    maxWorkflowInputs: 200
    maxWorkflowOutputs: 300
    minSecondsBetweenRunStatusPolls: 30
    maxSmartPollRunUpdateSeconds: 3
    maxSmartPollRunSetUpdateSeconds: 6
    maxWorkflowsInBatch: 100
  scheduler:
    # How often to check downstream services for health:
    healthCheckIntervalSeconds: 300

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator
      path-mapping:
          info: info
          health: health
  endpoint:
    health:
      show-details: ALWAYS

workflow-engines:
  cromwell:
    # This value comes from the config.
    baseUri: "http://localhost:8000"
    # Set this value to false for local testing.
    fetchCromwellUrlFromLeo: true
    # For local testing, you can supply a value here. If unsupplied, we will fall back to looking up in Leonardo
    debugApiLogging: false

wds:
  # For local testing, you can supply a value here. If unsupplied, we will fall back to looking up in Leonardo
  # baseUri: "http://localhost:8001"
  instanceId: "15f36863-30a5-4cab-91f7-52be439f1175"
  apiV: "v0.2"
  debugApiLogging: false

leonardo:
  baseUri: "https://leonardo.dsde-dev.broadinstitute.org/"
  # The below appTypeNames are in priority order for the named app type. This order is necessary for
  # the appComparisonFunction() located in AppUtils.java for selecting the best app for each app type.
  wdsAppTypeNames: ['WDS', 'CROMWELL'] # keeping CROMWELL type for backwards compatibility
  cromwellRunnerAppTypeNames: ['CROMWELL_RUNNER_APP', 'CROMWELL'] # keeping CROMWELL type for backwards compatibility
  dependencyUrlCacheTtlSeconds: 300 # Refresh every 5 minutes
  debugApiLogging: false

dockstore:
  baseUri: "https://staging.dockstore.org/"

github:
  personalAccessToken: "<insert personal access token here>"
  # ::IMPORTANT::
  # While testing, make sure the scopes of the personalAccessToken are limited to readonly access
  #   to a single repository.
  # This configuration will disappear as soon as we can connect with ECM
  #   to retrieve the token manually.

credentials:
  azure:
    tokenAcquisitionTimeoutSeconds: 5
    tokenCacheTtlSeconds: 300 # Refresh every 5 minutes
    # For local testing, you can supply a manual token override to avoid token acquisition logic:
    # manualTokenOverride: ""

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}

sam:
  baseUri: "https://sam.dsde-dev.broadinstitute.org/"
  debugApiLogging: false
  # this should be same as "wds.instanceId"
  workspaceId: "15f36863-30a5-4cab-91f7-52be439f1175"
  # for local testing this can be set to false
  checkAuthAccess: true

ecm:
  baseUri: "https://externalcreds.dsde-dev.broadinstitute.org/"
  debugApiLogging: false
