logging:
  level.bio.terra.cbas: ${BATCHANALYSIS_LOG_LEVEL:debug}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: cbas
  application.version: ${cbas.version.gitHash:unknown}
  datasource:
    jdbc-url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    username: ${DATABASE_USER:cbas_user}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
  sql:
    init:
      mode: always


  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null # this prevents a problem serializing VisaCriterion in openapi where `type` is included a second time with null value

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
  liquibase:
    change-log: changelog/changelog.yaml

cbas:
  cbas-database:
    uri: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
    username: ${DATABASE_USER:cbas_user}
  cbas-api:
    # for POST/run_sets, the number of record IDs must be less than or equal to this value.
    runSetsMaximumRecordIds: 100
    maxWorkflowInputs: 100
    maxWorkflowOutputs: 40
    minSecondsBetweenRunStatusPolls: 30
    maxSmartPollRunUpdateSeconds: 3
    maxSmartPollRunSetUpdateSeconds: 6

workflow-engines:
  cromwell:
    baseUri: "http://localhost:8000"
    healthUri: "http://localhost:8000/engine/v1/status"

wds:
  baseUri: "http://localhost:8001"
  healthcheckEndpoint: "/swagger/swagger-ui.html"
  instanceId: "15f36863-30a5-4cab-91f7-52be439f1175"
  apiV: "v0.2"

leonardo:
  baseUri: "https://leonardo.dsde-dev.broadinstitute.org/"
  wdsAppTypeName: 'CROMWELL'

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
