logging:
  level.bio.terra.cbas: ${BATCHANALYSIS_LOG_LEVEL:info}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: cbas
  application.version: ${cbas.version.gitHash:unknown}
  datasource:
    jdbc-url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    username: ${DATABASE_USER:cbas_user}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
  sql:
    init:
      mode: always


  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null # this prevents a problem serializing VisaCriterion in openapi where `type` is included a second time with null value

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
  liquibase:
    change-log: changelog/changelog.yaml

cbas:
  cbas-database:
    uri: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:cbas_db}
    password: ${DATABASE_USER_PASSWORD:cbas_password}
    username: ${DATABASE_USER:cbas_user}
  cbas-api:
    # for POST/run_sets, the number of record IDs must be less than or equal to this value.
    runSetsMaximumRecordIds: 100
    maxWorkflowInputs: 200
    maxWorkflowOutputs: 300
    minSecondsBetweenRunStatusPolls: 30
    maxSmartPollRunUpdateSeconds: 3
    maxSmartPollRunSetUpdateSeconds: 6
  scheduler:
    # How often to check downstream services for health:
    healthCheckIntervalSeconds: 300

workflow-engines:
  cromwell:
    # For local testing, you can supply a value here. If unsupplied, we will fall back to looking up in Leonardo
    # baseUri: "http://localhost:8000"
    debugApiLogging: false

wds:
  # For local testing, you can supply a value here. If unsupplied, we will fall back to looking up in Leonardo
  # baseUri: "http://localhost:8001"
  instanceId: "15f36863-30a5-4cab-91f7-52be439f1175"
  apiV: "v0.2"
  debugApiLogging: false

leonardo:
  baseUri: "https://leonardo.dsde-dev.broadinstitute.org/"
  appTypeNames: ['WDS', 'CROMWELL', 'WORKFLOWS_APP', 'CROMWELL_RUNNER_APP'] # keeping CROMWELL for backwards compatibility
  dependencyUrlCacheTtlSeconds: 300 # Refresh every 5 minutes
  debugApiLogging: false

dockstore:
  baseUri: "https://staging.dockstore.org/"

credentials:
  azure:
    tokenAcquisitionTimeoutSeconds: 5
    tokenCacheTtlSeconds: 300 # Refresh every 5 minutes
    # For local testing, you can supply a manual token override to avoid token acquisition logic:
    # manualTokenOverride: "eyJhbGciOiJSUzI1NiIsImtpZCI6Inp4UnJ6aEw4OTBrYi1vVkZOWkdWUFlxSzYtSkI3RFRlTGVvMllTbzRtc1UiLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6ImRvbnR0ZXN0bWUua29hbGFAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkthdHJpbmEiLCJmYW1pbHlfbmFtZSI6IlBpZXJyZSIsIm5hbWUiOiJLYXRyaW5hIFBpZXJyZSIsImlkcCI6Imdvb2dsZS5jb20iLCJpZHBfYWNjZXNzX3Rva2VuIjoieWEyOS5hMEFmQl9ieUNpSUtYZWZPaEhvT3pkLXh1NlRHbjVJMGxydjNURFNocGlyQVRXQTh4WGhCREN2MHRHNGVsdC1RMVltM2c4OEZhTDg5RjhmRzBia3hKbC15WXZlR0JxMXRyVEpTLTA4aS1hYlhUX1ZneEpLN3BZZ21adENPeHNHYXU3YXdjQ1Q0NWlsVmhzeU1ZR2pDTnBzekRkSTI2TXphY2FDZ1lLQWRFU0FSSVNGUUhzdllsc20xQXpWVi1Pb09QRE1pb3IyUGxOdVEwMTY2IiwiZ29vZ2xlX2lkIjoiMTA1NDE1NTY0MTY2MDk3NzM5NDkwIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGN3US1XdDRZQ2dSaDFOMTNaQWs0Q2NGaG5GQ3JqNzJMR0ttX19ZTXNSRD1zOTYtYyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJzdWIiOiJjZmY1NTY5MS04OTI4LTRiODAtOGFhZC02ZDc2YmM1OTcxZjAiLCJ0aWQiOiJmZDBiYzBlZi0xNzQ3LTRlZTYtYWIzZS1kNGQ2YmI4ODJkNDAiLCJhenAiOiJiYmQwN2Q0My0wMWNiLTRiNjktOGZkMC01NzQ2ZDlhNWM5ZmUiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2OTIwMzIwMjIsImF1ZCI6ImJiZDA3ZDQzLTAxY2ItNGI2OS04ZmQwLTU3NDZkOWE1YzlmZSIsImV4cCI6MTY5MjAzNTYyMiwiaXNzIjoiaHR0cHM6Ly90ZXJyYWRldmIyYy5iMmNsb2dpbi5jb20vZmQwYmMwZWYtMTc0Ny00ZWU2LWFiM2UtZDRkNmJiODgyZDQwL3YyLjAvIiwibmJmIjoxNjkyMDMyMDIyfQ.Cgrqbc4cLKB52_uob3rBPBaYw4tHdySMrc8f15aeBegG_VQO-U815WwEBABZrx2LojYA_0Il5owI6JK1wFYCzWJ5hFqYRb3BhsKiHp1vEIz3J6ihZCsNcWgcY7rCMUQgYE2IdBZrFjNPqynHWODMke1ZJPP-YMwKxj5z_KgRf7Nra2PXAZAmLlJDRHO7ZvUXnmwEO5H3vQ7UkApQbdq6oRscihWoZrGHXV9Ep7H7Yh7BdubMJ8vmxDM9moCbFFYlaHO-1NgA52PqSbD1irpByblOo7uHsPT4_VkzUqcTXfQYLFLagvZAlru9dfBvN27Cii6E7073s621L3s0ZstWqQ"

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}

sam:
  baseUri: "https://sam.dsde-dev.broadinstitute.org/"
  debugApiLogging: false
