openapi: 3.0.3
info:
  title: Terra Batch Analysis
  description: Manage batch analyses, run configurations, and run sets in userspace
  version: 0.0.1
servers:
  - url: ./
    description: Relative to the current swagger page
paths:
  /status:
    get:
      summary: Check status of the service
      tags: [ public ]
      operationId: getStatus
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/SystemStatusResponse'
  "/api/batch/v1/runs":
    get:
      tags: [ runs ]
      summary: Get list of all runs
      operationId: getRuns
      responses:
        '200':
          $ref: '#/components/responses/GetRunResponse'
        '400':
          $ref: '#/components/responses/UserError'
        '500':
          $ref: '#/components/responses/ServerError'
  /api/batch/v1/run_sets:
    post:
      tags: [ run_sets ]
      summary: Combine an inputs definition with WDS entities to run a series of workflows
      operationId: postRunSet
      requestBody:
        $ref: '#/components/requestBodies/PostRunSetRequest'
      responses:
        '200':
          $ref: '#/components/responses/PostRunSetResponse'
        '201':
          $ref: '#/components/responses/PostRunSetResponse'
        '400':
          $ref: '#/components/responses/UserError'
        '500':
          $ref: '#/components/responses/ServerError'
  /api/batch/v1/methods:
    get:
      summary: Lists known methods
      tags: [ batch ]
      operationId: listMethods
      responses:
        '200':
          description: A JSON array of methods
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          $ref: '#/components/responses/ServerError'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  requestBodies:
    PostRunSetRequest:
      description: Request body to run a set of workflows (by URL) with WDS inputs.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RunSetRequest'

  responses:
    PostRunSetResponse:
      description: Response from creating a new run set
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RunSetStateResponse'
    GetRunResponse:
      description: Details about runs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RunLogResponse'
    SystemStatusResponse:
      description: A JSON description of the subsystems and their statuses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'
    UserError:
      description: User error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:
    RunSetRequest:
      type: object
      properties:
        workflow_url:
          type: string
          description: URL to the workflow script to run
          example: 'https://www.example.com/example.wdl'
        workflow_param_definitions:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowParamDefinition'
          description: Declarative input definition for combination with WDS entities
        wds_entities:
          $ref: '#/components/schemas/WdsEntitySet'
        workflow_output_definitions:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowOutputDefinition'

    WdsEntitySet:
      type: object
      properties:
        entity_type:
          type: string
          example: FOO
        entity_ids:
          type: array
          items:
            type: string
          example:
            - F0011111-1111-1111-1111-111111111111
      description: The set of WDS entities to use when constructing the inputs.

    WorkflowParamDefinition:
      type: object
      properties:
        parameter_name:
          type: string
          example: workflow_input_foo_rating
        parameter_type:
          $ref: '#/components/schemas/ParameterValueType'
        source:
          $ref: '#/components/schemas/ParameterDefinition'

    WorkflowOutputDefinition:
      type: object
      properties:
        output_name:
          type: string
          example: workflow_output_foo_rating
        output_type:
          $ref: '#/components/schemas/ParameterValueType'
        entity_attribute:
          type: string
          description: The attribute name on the entity to use.
          required: true
          example: entity_field_foo_rating

    ParameterValueType:
      title: ParameterValueType
      example: String
      description: What type of value this parameter expects
      enum:
        - String
        - Int
        - Boolean
        - Float
      type: string

    # This ParameterDefinition holds the 'oneOf' declaration for all the various types that can
    # be used as parameter definitions.
    # In addition, in Java it acts as the superclass for the various
    # ParameterDefinitionXYZ classes below. Because the codegen is imperfect, we have to explicitly
    # add 'allOf: ParameterDefinition' declarations to those classes to force the codegen to make
    # them subclasses... but in terms of how the swagger UI works, they seem to make no difference
    ParameterDefinition:
      title: ParameterDefinition
      properties:
        # Note: In quotes to remind us that this "type" is an API field, not an OpenAPI spec 'type':
        "type":
          type: string
          description: Indicates what type of parameter declaration this is.
          required: true
          enum: [ literal, entity_lookup ]
          example: entity_lookup
      oneOf:
        - $ref: '#/components/schemas/ParameterDefinitionEntityLookup'
        - $ref: '#/components/schemas/ParameterDefinitionLiteralValue'
      discriminator:
        propertyName: "type"
        mapping:
          literal: 'ParameterDefinitionLiteralValue'
          entity_lookup: 'ParameterDefinitionEntityLookup'

    ParameterDefinitionLiteralValue:
      type: object
      allOf:
        - $ref: '#/components/schemas/ParameterDefinition'
      properties:
        parameter_value:
          description: The literal value to use. Can be any type, but must match the declared parameter_type.
          required: True
          example: hello world
    ParameterDefinitionEntityLookup:
      type: object
      allOf:
        - $ref: '#/components/schemas/ParameterDefinition'
      properties:
        entity_attribute:
          type: string
          description: The attribute name on the entity to use.
          required: true
          example: entity_field_foo_rating
    RunSetStateResponse:
      type: object
      required: [run_set_id]
      properties:
        run_set_id:
          type:
            string
          example: 00000000-0000-0000-0000-000000000000
        runs:
          type: array
          items:
            $ref: '#/components/schemas/RunStateResponse'
        state:
          $ref: '#/components/schemas/RunSetState'

    RunLog:
      type: object
      properties:
        run_id:
          type: string
        workflow_url:
          type: string
          description: URL to the workflow script to run
        name:
          type: string
        state:
          $ref: '#/components/schemas/RunState'
        workflow_params:
          type: string
        submission_date:
          type: string
          format: date-time
    RunLogResponse:
      type: object
      properties:
        runs:
          type: array
          items:
            $ref: '#/components/schemas/RunLog'
    RunStateResponse:
      type: object
      required: [run_id]
      properties:
        run_id:
          type:
            string
          example: 00000000-0000-0000-0000-000000000000
        state:
          $ref: '#/components/schemas/RunState'
    ErrorReport:
      type: object
      required: [ message, status_code, causes]
      properties:
        message:
          type: string
        status_code:
          type: integer
        causes:
          type: array
          items:
            type: string
    SystemStatus:
      required: [ ok, systems ]
      type: object
      properties:
        ok:
          type: boolean
          description: whether any system(s) need attention
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string
    RunState:
      title: RunState
      example: QUEUED
      enum:
        - UNKNOWN
        - QUEUED
        - INITIALIZING
        - RUNNING
        - PAUSED
        - COMPLETE
        - EXECUTOR_ERROR
        - SYSTEM_ERROR
        - CANCELED
        - CANCELING
      type: string
    RunSetState:
      title: RunSetState
      example: RUNNING
      enum:
        - SET_UNKNOWN_STATE
        - SET_RUNNING
        - SET_COMPLETE
        - SET_ERROR
      type: string
