openapi: 3.0.3
info:
  title: Terra Batch Analysis
  description: Manage batch analyses, workflows, and submissions in userspace
  version: 0.0.1
paths:
  /api/batch/v1/methods:
    get:
      summary: Lists known methods
      tags: [ batch ]
      operationId: listMethods
      responses:
        '200':
          description: A JSON array of methods
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          $ref: '#/components/responses/ServerError'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:

    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:

    ErrorReport:
      type: object
      required: [ message, statusCode ]
      properties:
        message:
          type: string
        statusCode:
          type: integer
