name: Consumer contract tests
# The purpose of this workflow is to validate the service level contract
# using the Pact framework.
#
# More details on Contract Testing can be found in our handbook
#
# https://broadworkbench.atlassian.net/wiki/spaces/IRT/pages/2660368406/Getting+Started+with+Pact+Contract+Testing
#
#
#
# NOTE: The publish-contracts workflow will use the latest commit of the branch that triggers this workflow to publish the unique consumer contract version to Pact Broker.

on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

jobs:
  cbas-contract-tests:
    runs-on: ubuntu-latest
    outputs:
      pact-b64: ${{ steps.encode-pact.outputs.pact-b64 }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run consumer tests
        run: ./gradlew pactTests
      - name: Output consumer contract as non-breaking base64 string
        id: encode-pact
        run: |
          NON_BREAKING_B64=$(cat service/build/pacts/cbas-sam-provider.json | base64 -w 0)
          echo "pact-b64=${NON_BREAKING_B64}" >> $GITHUB_OUTPUT

  publish-contracts:
    runs-on: ubuntu-latest
    needs: [ cbas-consumer-contract-tests ]
    steps:
      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v3
        with:
          workflow: .github/workflows/publish-contracts.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN }} # GitHub token for access to kick off a job in the private repo
          inputs: '{ "pact-b64": "${{ needs.cbas-consumer-contract-tests.outputs.pact-b64 }}", "repo-owner": "DataBiosphere", "repo-name": "cbas", "repo-branch": "main" }'

## Deactivated until WM-2191 lands
#  can-i-deploy:
#    runs-on: ubuntu-latest
#    needs: [ init-github-context, publish-contracts ]
#    steps:
#      - name: Dispatch to terra-github-workflows
#        uses: broadinstitute/workflow-dispatch@v3
#        with:
#          workflow: .github/workflows/can-i-deploy.yaml
#          repo: broadinstitute/terra-github-workflows
#          ref: refs/heads/main
#          token: ${{ secrets.BROADBOT_TOKEN }} # GitHub token for access to kick off a job in the private repo
#          inputs: '{ "pacticipant": "cbas-consumer", "version": "${{ needs.init-github-context.outputs.repo-version }}" }'
