name: Tag and publish

# Note: Adapted from terra-data-catalog.
# For future functionality like 'publish to Artifactory', 'push to GCR', ..., see the data catalog version of this file.

on:
  workflow_call:
    secrets:
      BROADBOT_TOKEN:
        required: true
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      DSDEJENKINS_DOCKERHUB_PASSWORD:
        required: true

env:
  SERVICE_NAME: cbas
  DOCKERHUB_ORG: broadinstitute
  GOOGLE_PROJECT: broad-dsp-gcr-public

jobs:
  tag-and-publish-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Fetch Jira ID from commit message
        env:
          COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
        id: ensure-jira-id
        run: |
          JIRA_ID=$(echo "$COMMIT_MESSAGE" | grep -Eo '[A-Z][A-Z]+-[0-9]+' | xargs echo -n | tr '[:space:]' ',')
          [[ -z "$JIRA_ID" ]] && { echo "No Jira ID found in $1" ; exit 1; }
          echo ::set-output name=JIRA_ID::${JIRA_ID}
      - name: Checkout current code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_TOKEN }} # this allows the push to succeed later
      - id: dispatch-tag
        name: Dispatch tag
        uses: ./.github/workflows/tag.yml
        with:
          release-branches: main
        secrets:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Print tag
        run: |
          echo ${{ steps.dispatch-tag.outputs.new-tag }}
      - name: Publish to Artifactory
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: ./gradlew --build-cache :client:artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: "libs-release-local"

      - name: Construct dockerhub and GCR image names
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        id: image-name
        run: |
          echo ::set-output name=DOCKERHUB_NAME::${DOCKERHUB_ORG}/${SERVICE_NAME}:${{ steps.dispatch-tag.outputs.new-tag }}
          echo ::set-output name=GCR_NAME::us.gcr.io/${GOOGLE_PROJECT}/${SERVICE_NAME}:${{ steps.dispatch-tag.outputs.new-tag }}

      - name: Build image locally with jib
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: |
          ./gradlew --build-cache :service:jibDockerBuild \
          --image=${{ steps.image-name.outputs.DOCKERHUB_NAME }} \
          -Djib.console=plain

      - name: Run Trivy vulnerability scanner
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: ${{ steps.image-name.outputs.DOCKERHUB_NAME }}

      - name: Login to Docker Hub
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: docker/login-action@v1
        with:
          username: dsdejenkins
          password: ${{ secrets.DSDEJENKINS_DOCKERHUB_PASSWORD }}

      - name: Push dockerhub image
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: docker push ${{ steps.image-name.outputs.DOCKERHUB_NAME }}

      - name: Re-tag image for GCR
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: docker tag ${{ steps.image-name.outputs.DOCKERHUB_NAME }} ${{ steps.image-name.outputs.GCR_NAME }}

      - name: Set up gcloud
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: google-github-actions/setup-gcloud@v0

      - name: Authenticate to Google Cloud
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: 'google-github-actions/auth@v0'
        with:
          # Centralized in dsp-tools-k8s; ask in #dsp-devops-champions for help troubleshooting
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'gcr-publish@broad-dsp-gcr-public.iam.gserviceaccount.com'

      - name: Explicitly auth Docker for GCR
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: gcloud auth configure-docker --quiet

      - name: Push GCR image
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: docker push ${{ steps.image-name.outputs.GCR_NAME }}

      - name: Clone Cromwhelm
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: actions/checkout@v2
        with:
          repository: broadinstitute/cromwhelm
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
          path: cromwhelm

      - name: Update CBAS Helm Chart in cromwhelm
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          set -e
          cd cromwhelm
          git checkout main
          ls -la
          HELM_CUR_TAG=$(grep "/cbas:" terra-batch-libchart/values.yaml | sed "s,.*/cbas:,,")
          HELM_NEW_TAG=${{ steps.dispatch-tag.outputs.new-tag }}
          [[ -n "$HELM_CUR_TAG" && -n "$HELM_NEW_TAG" ]]
          # prefixing search and replacement text with 'cbas' is needed to avoid replacing tag for cbas-ui
          # when both cbas and cbas-ui have the same image version
          sed -i "s/cbas:$HELM_CUR_TAG/cbas:$HELM_NEW_TAG/" terra-batch-libchart/values.yaml
          git diff
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -am "${{ steps.ensure-jira-id.outputs.JIRA_ID }}: Auto update CBAS version to $HELM_NEW_TAG"
          git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/cromwhelm.git main
          cd -

      - name: Clone terra-helmfile
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        uses: actions/checkout@v3
        with:
          repository: broadinstitute/terra-helmfile
          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
          path: terra-helmfile

      - name: Update workflows-app in terra-helmfile
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        run: |
          set -e
          cd terra-helmfile
          HELM_CUR_TAG=$(grep "/cbas:" charts/workflows-app/values.yaml | sed "s,.*/cbas:,,")
          HELM_NEW_TAG=${{ steps.dispatch-tag.outputs.new-tag }}
          [[ -n "$HELM_CUR_TAG" && -n "$HELM_NEW_TAG" ]]
          sed -i "s/$HELM_CUR_TAG/$HELM_NEW_TAG/" charts/workflows-app/values.yaml
          cd -

      - name: Make PR in terra-helmfile
        if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          GH_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          set -e
          HELM_NEW_TAG=${{ steps.dispatch-tag.outputs.new-tag }}
          JIRA_ID=${{ steps.ensure-jira-id.outputs.JIRA_ID }}
          if [[ $JIRA_ID == "missing" ]]; then
            echo "JIRA_ID missing, PR to terra-helmfile will not be created"
            exit 0;
          fi
          cd terra-helmfile
          git checkout -b ${JIRA_ID}-cbas-update-${HELM_NEW_TAG}
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -am "${JIRA_ID}: Auto update CBAS to $HELM_NEW_TAG in workflows-app"
          git push -u origin ${JIRA_ID}-cbas-update-${HELM_NEW_TAG}
          gh pr create --title "${JIRA_ID}: auto update CBAS version to $HELM_NEW_TAG in workflows-app" --body "${JIRA_ID} helm chart update" --label "automerge"
          cd -
