name: Verify Pacts on Main

on:
  push:
    branches: [ main ]
    paths-ignore: [ '*.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build all projects without running tests
        run: ./gradlew --build-cache build -x test

  verify-pacts:
    needs: [ build ]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]

    steps:
      - uses: actions/checkout@v2
        # Needed by sonar to get the git history for the branch the PR will be merged into.
        with:
          fetch-depth: 0

      - name: Make sure Postgres is ready and init
        env:
          PGPASSWORD: postgres
        run: |
          pg_isready -h localhost -t 10
          psql -h localhost -U postgres -f ./common/postgres-init.sql

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Configure pact
        env:
          PACTBROKER_APPLICATION_YAML_B64: ${{ secrets.PACTBROKER_APPLICATION_YAML_B64 }}
        run: |
          mkdir -p ./service/src/test/resources
          echo $PACTBROKER_APPLICATION_YAML_B64 | base64 --decode >> ./service/src/test/resources/application.yml
          echo "PROVIDER_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "PROVIDER_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Verify pacts
        env:
          PACT_PROVIDER_BRANCH: ${{ env.PROVIDER_BRANCH }}
          PACT_PROVIDER_COMMIT: ${{ env.PROVIDER_COMMIT }}
        run: |
          echo "PACT_PROVIDER_BRANCH=${{ env.PROVIDER_BRANCH }}
          echo "PACT_PROVIDER_COMMIT=${{ env.PROVIDER_COMMIT }}
          ./gradlew --build-cache verifyPacts
